# Generated by Django 4.0.2 on 2022-03-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.CharField(default='https://pic-1300286858.cos.ap-nanjing.myqcloud.com/uPic/2022-03/IpXB4h.png', max_length=255, verbose_name='标题图'),
        ),
    ]
